/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.InputData;
import model.GlobalVariables;

import javax.swing.*;
import java.util.Locale;

/**
 *
 * @author arturkowalczyk
 */
public class EditSelectedProduct extends javax.swing.JFrame {

    /**
     * Creates new form EditProductForm
     */
    public EditSelectedProduct() {
        initComponents();
        InputData data = new GlobalVariables().getProduct();
        jTextFieldMaximalProductPrice.setText(String.valueOf(data.getMaxPrice()));
        jTextFieldMinimalProductPrice.setText(String.valueOf(data.getMinPrice()));
        jTextFieldMinimalSellerReputation.setText(String.valueOf(data.getSellerReputation()));
        jTextFieldProductName.setText(data.getProductName());
        jTextFieldNumberOfProduct.setText(String.valueOf(data.getNumberOfItem()));
        if(data.isNew()){
            jComboBoxProductCondition.setSelectedItem("New");
        } else {
            jComboBoxProductCondition.setSelectedItem("Used");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanelData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jTextFieldMinimalSellerReputation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMinimalProductPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMaximalProductPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxProductCondition = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButtonReturnToMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNumberOfProduct = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 217, 222));

        jPanel3.setBackground(new java.awt.Color(214, 217, 222));

        jPanelData.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Product name");

        jTextFieldProductName.setMinimumSize(new java.awt.Dimension(10, 100));
        jTextFieldProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductNameActionPerformed(evt);
            }
        });

        jTextFieldMinimalSellerReputation.setMinimumSize(new java.awt.Dimension(10, 100));
        jTextFieldMinimalSellerReputation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinimalSellerReputationActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Minimal seller reputation");

        jTextFieldMinimalProductPrice.setMinimumSize(new java.awt.Dimension(10, 100));
        jTextFieldMinimalProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinimalProductPriceActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Minimal price");

        jTextFieldMaximalProductPrice.setMinimumSize(new java.awt.Dimension(10, 100));
        jTextFieldMaximalProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaximalProductPriceActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Maximal price");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Product condition");

        jComboBoxProductCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Used", " ", " ", " " }));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-question_mark.png"))); // NOI18N
        jLabel6.setToolTipText("0-100");

        jButtonReturnToMenu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButtonReturnToMenu.setText("Edit product");
        jButtonReturnToMenu.setToolTipText("");
        jButtonReturnToMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonReturnToMenuMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Number of product");

        jTextFieldNumberOfProduct.setMinimumSize(new java.awt.Dimension(10, 100));
        jTextFieldNumberOfProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumberOfProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDataLayout = new javax.swing.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNumberOfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)
                        .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonReturnToMenu)
                            .addGroup(jPanelDataLayout.createSequentialGroup()
                                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDataLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(11, 11, 11)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6))
                                        .addGroup(jPanelDataLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(114, 114, 114)))
                                    .addGroup(jPanelDataLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDataLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(91, 91, 91)))
                                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldMinimalProductPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldProductName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMinimalSellerReputation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMaximalProductPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxProductCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldMinimalSellerReputation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMinimalProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaximalProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumberOfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProductCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonReturnToMenu)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(214, 217, 222));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-edit.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 89, 3));
        jLabel9.setText("Edit product");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16)))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumberOfProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumberOfProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumberOfProductActionPerformed

    private void jButtonReturnToMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReturnToMenuMousePressed
        // TODO add your handling code here:
        InputData temp = new InputData();

        temp.setProductName(jTextFieldProductName.getText());

        try {
            String s = jTextFieldMinimalSellerReputation.getText();
            int i = Integer.parseInt(s.trim());
            if(i < 0 || i > 100) throw new Exception();
            temp.setSellerReputation(i);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"Enter integer.");
            jTextFieldMinimalSellerReputation.setText("");
            return;
        } catch (Exception e1) {
            JOptionPane.showMessageDialog(null, "Enter number in range 0-100.");
            jTextFieldMinimalSellerReputation.setText("");
            return;
        }

        try {
            String sf = jTextFieldMinimalProductPrice.getText().replace(",",".");
            String st = jTextFieldMaximalProductPrice.getText().replace(",",".");
            if(sf.equals("") && st.equals("")){
                temp.setMinPrice(0);
                temp.setMaxPrice(Float.MAX_VALUE);
            } else if(st.equals("")) {
                float ff = Float.parseFloat(sf);
                temp.setMinPrice(ff);
                temp.setMaxPrice(Float.MAX_VALUE);
            } else {
                float ff = Float.parseFloat(sf);
                float ft = Float.parseFloat(st);
                boolean b = sf.matches("-?\\d+(\\.\\d+)?");
                boolean b1 = (ff < ft);
                if (b) jTextFieldMinimalProductPrice.setText(String.format(Locale.US, "%.2f", ff));
                if (!b1) {
                    JOptionPane.showMessageDialog(null, "Number in Maximum price field have to be bigger \nthan in Minimum price field.");
                    return;
                }
                if (ff < 0) throw new Exception();
                temp.setMinPrice(ff);
                temp.setMaxPrice(ft);
            }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Enter number.");
            jTextFieldMinimalProductPrice.setText("");
            return;
        }
        catch (Exception e1){
            JOptionPane.showMessageDialog(null,"Enter number greater than 0.");
            jTextFieldMinimalProductPrice.setText("");
            return;
        }

        try {
            String s = jTextFieldNumberOfProduct.getText();
            if (s.equals("")){
                temp.setNumberOfItem(1);
            }else {
                int i = Integer.parseInt(s.trim());
                if (i <= 0) throw new Exception();
                temp.setNumberOfItem(i);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"Enter integer.");
            jTextFieldMinimalSellerReputation.setText("");
            return;
        } catch (Exception e1) {
            JOptionPane.showMessageDialog(null, "Enter number greater than 0.");
            jTextFieldMinimalSellerReputation.setText("");
            return;
        }

        if(jComboBoxProductCondition.getSelectedItem().toString().equals("New")){
            temp.setNew(true);
        } else {
            temp.setNew(false);
        }
        if(jComboBoxProductCondition.getSelectedItem().toString().equals("New")){
            temp.setNew(true);
        } else {
            temp.setNew(false);
        }
        new GlobalVariables().addProduct(temp);
        new GlobalVariables().removeProduct();

        setVisible(false);
        dispose();
        new EditProduct().show();

    }//GEN-LAST:event_jButtonReturnToMenuMousePressed

    private void jTextFieldMaximalProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaximalProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaximalProductPriceActionPerformed

    private void jTextFieldMinimalProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinimalProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinimalProductPriceActionPerformed

    private void jTextFieldMinimalSellerReputationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinimalSellerReputationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinimalSellerReputationActionPerformed

    private void jTextFieldProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSelectedProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSelectedProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSelectedProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSelectedProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSelectedProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReturnToMenu;
    private javax.swing.JComboBox<String> jComboBoxProductCondition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JTextField jTextFieldMaximalProductPrice;
    private javax.swing.JTextField jTextFieldMinimalProductPrice;
    private javax.swing.JTextField jTextFieldMinimalSellerReputation;
    private javax.swing.JTextField jTextFieldNumberOfProduct;
    private javax.swing.JTextField jTextFieldProductName;
    // End of variables declaration//GEN-END:variables
}
