/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.*;
import controller.AllegroAPIRequest;
import controller.BestOptions;

import javax.swing.*;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;

/**
 *
 * @author arturkowalczyk
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAddProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelEditProduct = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelSearchProducts = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/allegro.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanelAddProduct.setBackground(new java.awt.Color(214, 217, 222));
        jPanelAddProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 89, 3)));
        jPanelAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelAddProductMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAddProductMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAddProductMouseEntered(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-add.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add product");

        javax.swing.GroupLayout jPanelAddProductLayout = new javax.swing.GroupLayout(jPanelAddProduct);
        jPanelAddProduct.setLayout(jPanelAddProductLayout);
        jPanelAddProductLayout.setHorizontalGroup(
            jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddProductLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddProductLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(27, 27, 27))
        );
        jPanelAddProductLayout.setVerticalGroup(
            jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelEditProduct.setBackground(new java.awt.Color(214, 217, 222));
        jPanelEditProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 89, 3)));
        jPanelEditProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelEditProductMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEditProductMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEditProductMouseEntered(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-edit.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edit product");

        javax.swing.GroupLayout jPanelEditProductLayout = new javax.swing.GroupLayout(jPanelEditProduct);
        jPanelEditProduct.setLayout(jPanelEditProductLayout);
        jPanelEditProductLayout.setHorizontalGroup(
            jPanelEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditProductLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanelEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditProductLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditProductLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25))))
        );
        jPanelEditProductLayout.setVerticalGroup(
            jPanelEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSearchProducts.setBackground(new java.awt.Color(214, 217, 222));
        jPanelSearchProducts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 89, 3)));
        jPanelSearchProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                try {
                    jPanelSearchProductsMousePressed(evt);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSearchProductsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSearchProductsMouseEntered(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-submit_for_approval.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search");

        javax.swing.GroupLayout jPanelSearchProductsLayout = new javax.swing.GroupLayout(jPanelSearchProducts);
        jPanelSearchProducts.setLayout(jPanelSearchProductsLayout);
        jPanelSearchProductsLayout.setHorizontalGroup(
            jPanelSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchProductsLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanelSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanelSearchProductsLayout.setVerticalGroup(
            jPanelSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanelAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addComponent(jPanelSearchProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearchProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelSearchProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSearchProductsMouseEntered
        // TODO add your handling code here:
        setColor(jPanelSearchProducts);
    }//GEN-LAST:event_jPanelSearchProductsMouseEntered

    private void jPanelSearchProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSearchProductsMouseExited
        // TODO add your handling code here:
        resetColor(jPanelSearchProducts);
    }//GEN-LAST:event_jPanelSearchProductsMouseExited

    private void jPanelSearchProductsMousePressed(java.awt.event.MouseEvent evt) throws InterruptedException {//GEN-FIRST:event_jPanelSearchProductsMousePressed
        // TODO add your handling code here:
        if (new GlobalVariables().getProductList().size() > 0){
            System.out.println("Search");
            setVisible(false);
            dispose();
            new FrameWithProgressBar().show();
            new GlobalVariables().setStartTimeOfMakingRequests(System.currentTimeMillis());

            SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() throws Exception {
                    ArrayList<Thread> threads = new ArrayList<>();

                    for (int i = 0; i < (new GlobalVariables().getProductList()).size(); i++) {
                        InputData data = new GlobalVariables().getProductList().get(i);
                        data.setProductFlag(i + 1);
                        try {
                            threads.add(new Thread(new AllegroAPIRequest(data)));
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        } catch (IOException e) {
                            e.printStackTrace();
                        } catch (URISyntaxException e) {
                            e.printStackTrace();
                        }
                        threads.get(i).start();
                    }
                    System.out.println(3);

                    for (int j = 0; j < threads.size(); j++) { //wait for all thread to complete their tasks
                        try {
                            threads.get(j).join();
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }

                    BestOptions bestOption = new BestOptions(AllegroAPIRequest.getCompleteOffersList());
                    new GlobalVariables().setBestOptions(bestOption);
//                    System.out.println(System.currentTimeMillis() - new GlobalVariables().getStartTimeOfMakingRequests());
                    return null;
                }
            };

            worker.execute();

        } else {
            JOptionPane.showMessageDialog(null, "You have to add product first.");
        }

    }//GEN-LAST:event_jPanelSearchProductsMousePressed

    private void jPanelEditProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEditProductMouseEntered
        // TODO add your handling code here:
        setColor(jPanelEditProduct);
    }//GEN-LAST:event_jPanelEditProductMouseEntered

    private void jPanelEditProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEditProductMouseExited
        // TODO add your handling code here:
        resetColor(jPanelEditProduct);
    }//GEN-LAST:event_jPanelEditProductMouseExited

    private void jPanelEditProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEditProductMousePressed
        // TODO add your handling code here:
        System.out.println("Edit");
        new EditProduct().show();
    }//GEN-LAST:event_jPanelEditProductMousePressed

    private void jPanelAddProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddProductMouseEntered
        // TODO add your handling code here:
        setColor(jPanelAddProduct);
    }//GEN-LAST:event_jPanelAddProductMouseEntered

    private void jPanelAddProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddProductMouseExited
        // TODO add your handling code here:
        resetColor(jPanelAddProduct);
    }//GEN-LAST:event_jPanelAddProductMouseExited

    private void jPanelAddProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddProductMousePressed
        // TODO add your handling code here:
        System.out.println("Add");
        new AddProduct().show();
    }//GEN-LAST:event_jPanelAddProductMousePressed
                                       
    
 
    
    public void setColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }
    
    public void resetColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(214,217,222));
    }
    
    
    
    /** /Users/arturkowalczyk/NetBeansProjects/AllegroGUI/src/main/images/allegro.jpg
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAddProduct;
    private javax.swing.JPanel jPanelEditProduct;
    private javax.swing.JPanel jPanelSearchProducts;
    // End of variables declaration//GEN-END:variables
}
